name: Publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency: ${{ github.workflow }}-publish-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check that the version match the tag
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          if [ "$(node -p "require('./package.json').version")" != "${GITHUB_REF#refs/tags/v}" ]; then
            echo "Version in package.json does not match the tag"
            exit 1
          fi
      # Install dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      # Lint
      - name: Lint
        run: npm run lint
      # Build
      - name: Build
        run: npm run build
      # Publish
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
